// src/robots/RobotRegistry.js
// Complete AI Robot/Drone Registry with stats, abilities, and types

export const ROBOT_REGISTRY = {
  // COMBAT ROBOTS (3)
  robox_standard: {
    id: 'robox_standard',
    name: 'Robox Standard',
    type: 'combat_bot',
    category: 'ground',
    tier: 'common',
    hp: 2000,
    atk: 300,
    def: 50,
    speed: 140,
    cost: 1000,
    description: 'Standard Robox combat bot with balanced stats',
    color: '#5ba3ff',
    secondaryColor: '#5bffaa',
    abilities: ['Sword Slash', 'Energy Bolt', 'Triple Strike'],
    modes: ['follow', 'aggro', 'guard', 'assist'],
    targetModes: ['nearest', 'lowest', 'boss'],
    fireRate: 420,
    ranged: 320,
    melee: 90,
    width: 28,
    height: 70,
  },

  robox_elite: {
    id: 'robox_elite',
    name: 'Robox Elite',
    type: 'combat_bot',
    category: 'ground',
    tier: 'rare',
    hp: 3500,
    atk: 500,
    def: 100,
    speed: 160,
    cost: 3000,
    description: 'Elite version with enhanced weapons and shields',
    color: '#8a2be2',
    secondaryColor: '#ff69b4',
    abilities: ['Lightning Fan', 'Domain Pulse', 'Spiral Volley'],
    modes: ['follow', 'aggro', 'guard', 'assist'],
    targetModes: ['nearest', 'lowest', 'boss'],
    fireRate: 350,
    ranged: 400,
    melee: 110,
    width: 32,
    height: 75,
    hasShield: true,
  },

  robox_titan: {
    id: 'robox_titan',
    name: 'Robox Titan',
    type: 'combat_bot',
    category: 'ground',
    tier: 'legendary',
    hp: 5000,
    atk: 800,
    def: 200,
    speed: 120,
    cost: 8000,
    description: 'Massive combat bot with devastating firepower',
    color: '#ff4444',
    secondaryColor: '#ffff00',
    abilities: ['Mega Beam', 'Rocket Barrage', 'EMP Pulse', 'Overdrive'],
    modes: ['follow', 'aggro', 'guard', 'assist', 'rampage'],
    targetModes: ['nearest', 'lowest', 'boss', 'strongest'],
    fireRate: 600,
    ranged: 500,
    melee: 150,
    width: 45,
    height: 90,
    hasShield: true,
    hasHeavyWeapons: true,
  },

  // SUPPORT DRONES (3)
  drone_scout: {
    id: 'drone_scout',
    name: 'Scout Drone',
    type: 'support_drone',
    category: 'hover',
    tier: 'common',
    hp: 800,
    atk: 100,
    def: 20,
    speed: 200,
    cost: 500,
    description: 'Fast recon drone with light weapons',
    color: '#74b9ff',
    secondaryColor: '#00d4ff',
    abilities: ['Scan', 'Light Laser'],
    modes: ['follow', 'patrol', 'scout'],
    targetModes: ['nearest'],
    fireRate: 250,
    ranged: 280,
    melee: 0,
    width: 20,
    height: 20,
    isHovering: true,
  },

  drone_healer: {
    id: 'drone_healer',
    name: 'Repair Drone',
    type: 'support_drone',
    category: 'hover',
    tier: 'uncommon',
    hp: 1200,
    atk: 50,
    def: 30,
    speed: 140,
    cost: 1500,
    description: 'Healing support drone that repairs allies',
    color: '#5bffaa',
    secondaryColor: '#00ff88',
    abilities: ['Repair Beam', 'Shield Boost', 'Emergency Heal'],
    modes: ['follow', 'assist', 'guard'],
    targetModes: ['lowest_ally'],
    fireRate: 800,
    ranged: 200,
    melee: 0,
    width: 22,
    height: 22,
    isHovering: true,
    isSupport: true,
    healingPower: 150,
  },

  drone_shield: {
    id: 'drone_shield',
    name: 'Shield Drone',
    type: 'support_drone',
    category: 'hover',
    tier: 'rare',
    hp: 1800,
    atk: 0,
    def: 100,
    speed: 100,
    cost: 2500,
    description: 'Defensive drone that projects energy shields',
    color: '#00d4ff',
    secondaryColor: '#5ba3ff',
    abilities: ['Energy Shield', 'Barrier Wall', 'Reflect'],
    modes: ['follow', 'guard', 'defend'],
    targetModes: ['protect_player'],
    fireRate: 0,
    ranged: 0,
    melee: 0,
    width: 26,
    height: 26,
    isHovering: true,
    isSupport: true,
    shieldStrength: 500,
  },

  // SPECIALIZED UNITS (4)
  mech_assault: {
    id: 'mech_assault',
    name: 'Assault Mech',
    type: 'mech',
    category: 'ground',
    tier: 'epic',
    hp: 4000,
    atk: 600,
    def: 150,
    speed: 110,
    cost: 5000,
    description: 'Heavy mech with dual gatling guns',
    color: '#ff6b35',
    secondaryColor: '#ffd56a',
    abilities: ['Gatling Burst', 'Rocket Salvo', 'Ground Pound'],
    modes: ['follow', 'aggro', 'siege'],
    targetModes: ['nearest', 'boss'],
    fireRate: 200,
    ranged: 350,
    melee: 120,
    width: 50,
    height: 80,
    hasHeavyArmor: true,
  },

  sniper_bot: {
    id: 'sniper_bot',
    name: 'Sniper Bot',
    type: 'ranged_specialist',
    category: 'ground',
    tier: 'rare',
    hp: 1500,
    atk: 700,
    def: 40,
    speed: 100,
    cost: 3500,
    description: 'Long-range precision bot with railgun',
    color: '#c0392b',
    secondaryColor: '#ff6b6b',
    abilities: ['Railgun Shot', 'Charged Blast', 'Piercing Round'],
    modes: ['follow', 'snipe', 'overwatch'],
    targetModes: ['boss', 'highest_hp', 'nearest'],
    fireRate: 1200,
    ranged: 800,
    melee: 0,
    width: 30,
    height: 65,
    isSniperUnit: true,
  },

  stealth_bot: {
    id: 'stealth_bot',
    name: 'Stealth Bot',
    type: 'infiltrator',
    category: 'ground',
    tier: 'epic',
    hp: 1000,
    atk: 450,
    def: 30,
    speed: 220,
    cost: 4000,
    description: 'Cloaking assassin bot with backstab damage',
    color: '#2c3e50',
    secondaryColor: '#9b59b6',
    abilities: ['Cloak', 'Backstab', 'Smoke Bomb', 'Shadow Strike'],
    modes: ['follow', 'hunt', 'flank'],
    targetModes: ['lowest', 'isolated'],
    fireRate: 500,
    ranged: 250,
    melee: 140,
    width: 24,
    height: 60,
    canCloak: true,
    backstabMultiplier: 3,
  },

  engineer_bot: {
    id: 'engineer_bot',
    name: 'Engineer Bot',
    type: 'builder',
    category: 'ground',
    tier: 'uncommon',
    hp: 1600,
    atk: 150,
    def: 60,
    speed: 120,
    cost: 2000,
    description: 'Support bot that builds turrets and repairs structures',
    color: '#f39c12',
    secondaryColor: '#e67e22',
    abilities: ['Build Turret', 'Repair', 'Deploy Mine', 'Fortify'],
    modes: ['follow', 'assist', 'build'],
    targetModes: ['nearest'],
    fireRate: 600,
    ranged: 200,
    melee: 80,
    width: 32,
    height: 55,
    canBuild: true,
    maxTurrets: 3,
  },

  // ADVANCED UNITS (2)
  plasma_bot: {
    id: 'plasma_bot',
    name: 'Plasma Bot',
    type: 'energy_specialist',
    category: 'ground',
    tier: 'legendary',
    hp: 2500,
    atk: 900,
    def: 80,
    speed: 150,
    cost: 7000,
    description: 'Experimental bot with unstable plasma cannon',
    color: '#e74c3c',
    secondaryColor: '#ff9ff3',
    abilities: ['Plasma Burst', 'Fusion Wave', 'Overcharge', 'Meltdown'],
    modes: ['follow', 'aggro', 'overload'],
    targetModes: ['nearest', 'grouped', 'boss'],
    fireRate: 700,
    ranged: 450,
    melee: 0,
    width: 35,
    height: 70,
    unstable: true,
    aoeRange: 180,
  },

  ai_core: {
    id: 'ai_core',
    name: 'AI Core',
    type: 'command_unit',
    category: 'hover',
    tier: 'legendary',
    hp: 3000,
    atk: 400,
    def: 120,
    speed: 90,
    cost: 10000,
    description: 'Central AI that commands and buffs other robots',
    color: '#9b59b6',
    secondaryColor: '#3498db',
    abilities: ['Command', 'Buff Allies', 'Tactical Strike', 'System Override'],
    modes: ['follow', 'command', 'defend'],
    targetModes: ['strategic'],
    fireRate: 800,
    ranged: 350,
    melee: 0,
    width: 40,
    height: 40,
    isHovering: true,
    isCommander: true,
    buffRadius: 300,
    buffPower: 1.5,
  },
};

// Robot types and categories
export const ROBOT_TYPES = {
  combat_bot: { name: 'Combat Bot', icon: '🤖', color: '#5ba3ff' },
  support_drone: { name: 'Support Drone', icon: '🛸', color: '#74b9ff' },
  mech: { name: 'Mech', icon: '🦾', color: '#ff6b35' },
  ranged_specialist: { name: 'Sniper', icon: '🎯', color: '#c0392b' },
  infiltrator: { name: 'Stealth', icon: '👤', color: '#2c3e50' },
  builder: { name: 'Engineer', icon: '🔧', color: '#f39c12' },
  energy_specialist: { name: 'Plasma', icon: '⚡', color: '#e74c3c' },
  command_unit: { name: 'AI Core', icon: '🧠', color: '#9b59b6' },
};

export const ROBOT_CATEGORIES = {
  ground: { name: 'Ground', description: 'Ground-based combat units', types: ['combat_bot', 'mech', 'ranged_specialist', 'infiltrator', 'builder', 'energy_specialist'] },
  hover: { name: 'Hover', description: 'Hovering support and command units', types: ['support_drone', 'command_unit'] },
};

export const ROBOT_TIERS = {
  common: { name: 'Common', color: '#ffffff', stars: '⭐' },
  uncommon: { name: 'Uncommon', color: '#4CAF50', stars: '⭐⭐' },
  rare: { name: 'Rare', color: '#3498db', stars: '⭐⭐⭐' },
  epic: { name: 'Epic', color: '#9b59b6', stars: '⭐⭐⭐⭐' },
  legendary: { name: 'Legendary', color: '#f39c12', stars: '⭐⭐⭐⭐⭐' },
};

// Helper functions
export function getRobot(id) {
  return ROBOT_REGISTRY[id] || null;
}

export function getAllRobots() {
  return Object.values(ROBOT_REGISTRY);
}

export function getRobotsByType(type) {
  return Object.values(ROBOT_REGISTRY).filter(r => r.type === type);
}

export function getRobotsByTier(tier) {
  return Object.values(ROBOT_REGISTRY).filter(r => r.tier === tier);
}

export function getRobotsByCategory(category) {
  return Object.values(ROBOT_REGISTRY).filter(r => r.category === category);
}

