/**
 * AchievementExpansion.js - 50 Additional Achievements
 * @version 1.0.0
 * @description Expands achievement system from 50 to 100 total achievements
 */

(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    define([], factory);
  } else if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.AchievementExpansion = factory();
  }
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";

  // ============================
  // 50 NEW ACHIEVEMENTS (51-100)
  // ============================

  const NEW_ACHIEVEMENTS = {
    // HIDDEN ACHIEVEMENTS (10)
    secret_1: {
      id: "secret_1",
      name: "Easter Egg Hunter",
      description: "Find the hidden developer room",
      category: "hidden",
      icon: "🥚",
      requirement: { type: "secret_location", location: "dev_room" },
      reward: { gold: 10000, ap: 50 },
      hidden: true,
    },
    secret_2: {
      id: "secret_2",
      name: "Code Breaker",
      description: "Enter the secret konami code",
      category: "hidden",
      icon: "🎮",
      requirement: { type: "konami_code", value: 1 },
      reward: { gold: 5000, ap: 25 },
      hidden: true,
    },
    secret_3: {
      id: "secret_3",
      name: "Time Traveler",
      description: "Play at exactly midnight",
      category: "hidden",
      icon: "⏰",
      requirement: { type: "time_specific", hour: 0 },
      reward: { gold: 2000, ap: 10 },
      hidden: true,
    },
    secret_4: {
      id: "secret_4",
      name: "Lucky Number",
      description: "Level up to exactly level 77",
      category: "hidden",
      icon: "🎰",
      requirement: { type: "level", value: 77 },
      reward: { gold: 7777, ap: 77 },
      hidden: true,
    },
    secret_5: {
      id: "secret_5",
      name: "Pacifist",
      description: "Reach level 25 without killing any enemies",
      category: "hidden",
      icon: "☮️",
      requirement: { type: "pacifist_level", level: 25 },
      reward: { gold: 50000, ap: 100 },
      hidden: true,
    },
    secret_6: {
      id: "secret_6",
      name: "Minimalist",
      description: "Complete 10 waves with no equipment",
      category: "hidden",
      icon: "🧘",
      requirement: { type: "no_equipment_waves", value: 10 },
      reward: { gold: 25000, ap: 75 },
      hidden: true,
    },
    secret_7: {
      id: "secret_7",
      name: "Collector's Pride",
      description: "Collect one of every item in the game",
      category: "hidden",
      icon: "📚",
      requirement: { type: "complete_collection", value: 1 },
      reward: { gold: 100000, ap: 200 },
      hidden: true,
    },
    secret_8: {
      id: "secret_8",
      name: "Name Game",
      description: 'Name your character "Developer"',
      category: "hidden",
      icon: "💻",
      requirement: { type: "character_name", name: "Developer" },
      reward: { gold: 1000, ap: 5 },
      hidden: true,
    },
    secret_9: {
      id: "secret_9",
      name: "Millennium Player",
      description: "Play for 1000 hours total",
      category: "hidden",
      icon: "⏳",
      requirement: { type: "total_playtime", hours: 1000 },
      reward: { gold: 1000000, ap: 1000 },
      hidden: true,
    },
    secret_10: {
      id: "secret_10",
      name: "True Dedication",
      description: "Log in 365 days in a row",
      category: "hidden",
      icon: "📅",
      requirement: { type: "login_streak", days: 365 },
      reward: { gold: 365000, ap: 365 },
      hidden: true,
    },

    // CHALLENGE ACHIEVEMENTS (15)
    challenge_1: {
      id: "challenge_1",
      name: "Iron Man",
      description: "Complete 50 waves without dying once",
      category: "challenge",
      icon: "🛡️",
      requirement: { type: "no_death_waves", value: 50 },
      reward: { gold: 50000, ap: 100 },
    },
    challenge_2: {
      id: "challenge_2",
      name: "One Hit Wonder",
      description: "Defeat a boss in a single hit",
      category: "challenge",
      icon: "👊",
      requirement: { type: "one_hit_boss", value: 1 },
      reward: { gold: 25000, ap: 50 },
    },
    challenge_3: {
      id: "challenge_3",
      name: "Combo Master",
      description: "Achieve a 100+ hit combo",
      category: "challenge",
      icon: "🎯",
      requirement: { type: "max_combo", value: 100 },
      reward: { gold: 10000, ap: 30 },
    },
    challenge_4: {
      id: "challenge_4",
      name: "Speed Demon II",
      description: "Complete a wave in under 30 seconds",
      category: "challenge",
      icon: "⚡",
      requirement: { type: "wave_time", value: 30000 },
      reward: { gold: 15000, ap: 40 },
    },
    challenge_5: {
      id: "challenge_5",
      name: "Overkill",
      description: "Deal 100,000 damage in a single attack",
      category: "challenge",
      icon: "💥",
      requirement: { type: "single_hit_damage", value: 100000 },
      reward: { gold: 20000, ap: 50 },
    },
    challenge_6: {
      id: "challenge_6",
      name: "Multitasker",
      description: "Have 10 different status effects active at once",
      category: "challenge",
      icon: "🌀",
      requirement: { type: "simultaneous_effects", value: 10 },
      reward: { gold: 12000, ap: 35 },
    },
    challenge_7: {
      id: "challenge_7",
      name: "Boss Rush",
      description: "Defeat 10 bosses within 10 minutes",
      category: "challenge",
      icon: "⏱️",
      requirement: { type: "boss_rush", bosses: 10, time: 600000 },
      reward: { gold: 30000, ap: 70 },
    },
    challenge_8: {
      id: "challenge_8",
      name: "Underdog",
      description: "Defeat an enemy 50 levels higher than you",
      category: "challenge",
      icon: "🐕",
      requirement: { type: "level_gap_kill", gap: 50 },
      reward: { gold: 40000, ap: 80 },
    },
    challenge_9: {
      id: "challenge_9",
      name: "Lone Wolf",
      description: "Complete 100 waves solo",
      category: "challenge",
      icon: "🐺",
      requirement: { type: "solo_waves", value: 100 },
      reward: { gold: 25000, ap: 60 },
    },
    challenge_10: {
      id: "challenge_10",
      name: "Perfectionist",
      description: "Complete 10 perfect runs (no damage, no deaths)",
      category: "challenge",
      icon: "💯",
      requirement: { type: "perfect_runs", value: 10 },
      reward: { gold: 100000, ap: 150 },
    },
    challenge_11: {
      id: "challenge_11",
      name: "Elemental Chaos",
      description: "Use all 6 damage types in a single wave",
      category: "challenge",
      icon: "🌈",
      requirement: { type: "all_types_one_wave", value: 1 },
      reward: { gold: 8000, ap: 25 },
    },
    challenge_12: {
      id: "challenge_12",
      name: "Critical Mass",
      description: "Land 50 critical hits in a row",
      category: "challenge",
      icon: "💢",
      requirement: { type: "crit_streak", value: 50 },
      reward: { gold: 18000, ap: 45 },
    },
    challenge_13: {
      id: "challenge_13",
      name: "Survival Expert",
      description: "Survive with 1 HP for 60 seconds",
      category: "challenge",
      icon: "❤️",
      requirement: { type: "survive_1hp", seconds: 60 },
      reward: { gold: 15000, ap: 40 },
    },
    challenge_14: {
      id: "challenge_14",
      name: "Rank Destroyer",
      description: "Defeat one enemy of each rank (F to SSS+)",
      category: "challenge",
      icon: "🎖️",
      requirement: { type: "all_ranks_defeated", value: 15 },
      reward: { gold: 50000, ap: 100 },
    },
    challenge_15: {
      id: "challenge_15",
      name: "Never Lucky",
      description: "Complete 100 waves with 0 luck stat",
      category: "challenge",
      icon: "🍀",
      requirement: { type: "zero_luck_waves", value: 100 },
      reward: { gold: 35000, ap: 85 },
    },

    // MASTERY ACHIEVEMENTS (10)
    mastery_1: {
      id: "mastery_1",
      name: "Weapon Master",
      description: "Master all weapon types",
      category: "mastery",
      icon: "⚔️",
      requirement: { type: "weapon_mastery", value: 10 },
      reward: { gold: 20000, ap: 50 },
    },
    mastery_2: {
      id: "mastery_2",
      name: "Element Lord",
      description: "Deal 1M damage with each element type",
      category: "mastery",
      icon: "🔥",
      requirement: { type: "element_mastery", value: 6 },
      reward: { gold: 30000, ap: 75 },
    },
    mastery_3: {
      id: "mastery_3",
      name: "Status Specialist",
      description: "Apply every status effect 100 times",
      category: "mastery",
      icon: "✨",
      requirement: { type: "status_mastery", value: 35 },
      reward: { gold: 40000, ap: 90 },
    },
    mastery_4: {
      id: "mastery_4",
      name: "Talent Sage",
      description: "Unlock every talent in all lanes",
      category: "mastery",
      icon: "🧙",
      requirement: { type: "all_talents_unlocked", value: 1 },
      reward: { gold: 100000, ap: 200 },
    },
    mastery_5: {
      id: "mastery_5",
      name: "Equipment Expert",
      description: "Own a legendary item in every equipment slot",
      category: "mastery",
      icon: "👑",
      requirement: { type: "legendary_all_slots", value: 1 },
      reward: { gold: 50000, ap: 120 },
    },
    mastery_6: {
      id: "mastery_6",
      name: "Combat Veteran",
      description: "Win 10,000 battles",
      category: "mastery",
      icon: "🎖️",
      requirement: { type: "wins", value: 10000 },
      reward: { gold: 75000, ap: 150 },
    },
    mastery_7: {
      id: "mastery_7",
      name: "Loot Master",
      description: "Find at least one item of every rarity",
      category: "mastery",
      icon: "💎",
      requirement: { type: "all_rarities_found", value: 10 },
      reward: { gold: 25000, ap: 60 },
    },
    mastery_8: {
      id: "mastery_8",
      name: "Quest Legend",
      description: "Complete 500 total quests",
      category: "mastery",
      icon: "📜",
      requirement: { type: "quests_completed", value: 500 },
      reward: { gold: 60000, ap: 130 },
    },
    mastery_9: {
      id: "mastery_9",
      name: "Achievement Hunter",
      description: "Unlock 75 achievements",
      category: "mastery",
      icon: "🏆",
      requirement: { type: "achievements", value: 75 },
      reward: { gold: 80000, ap: 175 },
    },
    mastery_10: {
      id: "mastery_10",
      name: "Ultimate Mastery",
      description: "Reach max level, max prestige, and unlock all masteries",
      category: "mastery",
      icon: "👑",
      requirement: { type: "ultimate_mastery", value: 1 },
      reward: { gold: 999999, ap: 999 },
    },

    // PVP ACHIEVEMENTS (10)
    pvp_1: {
      id: "pvp_1",
      name: "First Victory",
      description: "Win your first PvP match",
      category: "pvp",
      icon: "🥇",
      requirement: { type: "pvp_wins", value: 1 },
      reward: { gold: 1000, ap: 5 },
    },
    pvp_2: {
      id: "pvp_2",
      name: "Gladiator",
      description: "Win 100 PvP matches",
      category: "pvp",
      icon: "⚔️",
      requirement: { type: "pvp_wins", value: 100 },
      reward: { gold: 20000, ap: 50 },
    },
    pvp_3: {
      id: "pvp_3",
      name: "Undefeated",
      description: "Win 10 PvP matches in a row",
      category: "pvp",
      icon: "🔥",
      requirement: { type: "pvp_win_streak", value: 10 },
      reward: { gold: 15000, ap: 40 },
    },
    pvp_4: {
      id: "pvp_4",
      name: "Arena Champion",
      description: "Reach rank 1 in the arena",
      category: "pvp",
      icon: "👑",
      requirement: { type: "arena_rank", value: 1 },
      reward: { gold: 50000, ap: 100 },
    },
    pvp_5: {
      id: "pvp_5",
      name: "Comeback King",
      description: "Win a PvP match with less than 10% HP",
      category: "pvp",
      icon: "🩹",
      requirement: { type: "pvp_comeback", value: 1 },
      reward: { gold: 10000, ap: 30 },
    },
    pvp_6: {
      id: "pvp_6",
      name: "Perfect Match",
      description: "Win a PvP match without taking damage",
      category: "pvp",
      icon: "💯",
      requirement: { type: "pvp_perfect", value: 1 },
      reward: { gold: 20000, ap: 50 },
    },
    pvp_7: {
      id: "pvp_7",
      name: "Tournament Victor",
      description: "Win a tournament",
      category: "pvp",
      icon: "🏆",
      requirement: { type: "tournament_wins", value: 1 },
      reward: { gold: 30000, ap: 75 },
    },
    pvp_8: {
      id: "pvp_8",
      name: "Domination",
      description: "Win 25 PvP matches in a single day",
      category: "pvp",
      icon: "⚡",
      requirement: { type: "pvp_wins_daily", value: 25 },
      reward: { gold: 25000, ap: 60 },
    },
    pvp_9: {
      id: "pvp_9",
      name: "Leaderboard Legend",
      description: "Stay in top 10 for a full week",
      category: "pvp",
      icon: "📊",
      requirement: { type: "top_ten_week", value: 1 },
      reward: { gold: 40000, ap: 90 },
    },
    pvp_10: {
      id: "pvp_10",
      name: "PvP Master",
      description: "Win 1000 PvP matches",
      category: "pvp",
      icon: "👑",
      requirement: { type: "pvp_wins", value: 1000 },
      reward: { gold: 100000, ap: 250 },
    },

    // SOCIAL ACHIEVEMENTS (5)
    social_1: {
      id: "social_1",
      name: "Team Player",
      description: "Win 50 co-op matches",
      category: "social",
      icon: "🤝",
      requirement: { type: "coop_wins", value: 50 },
      reward: { gold: 10000, ap: 30 },
    },
    social_2: {
      id: "social_2",
      name: "Helping Hand",
      description: "Revive teammates 100 times",
      category: "social",
      icon: "❤️",
      requirement: { type: "teammate_revives", value: 100 },
      reward: { gold: 15000, ap: 40 },
    },
    social_3: {
      id: "social_3",
      name: "Social Butterfly",
      description: "Add 50 friends",
      category: "social",
      icon: "🦋",
      requirement: { type: "friends", value: 50 },
      reward: { gold: 5000, ap: 15 },
    },
    social_4: {
      id: "social_4",
      name: "Trade Master",
      description: "Complete 100 trades with other players",
      category: "social",
      icon: "🤝",
      requirement: { type: "trades_completed", value: 100 },
      reward: { gold: 20000, ap: 50 },
    },
    social_5: {
      id: "social_5",
      name: "Guild Leader",
      description: "Create and maintain a guild for 30 days",
      category: "social",
      icon: "🏰",
      requirement: { type: "guild_leader_days", value: 30 },
      reward: { gold: 30000, ap: 75 },
    },
  };

  const NEW_ACHIEVEMENT_KEYS = Object.keys(NEW_ACHIEVEMENTS);

  // Export
  return {
    ACHIEVEMENTS: NEW_ACHIEVEMENTS,
    ACHIEVEMENT_KEYS: NEW_ACHIEVEMENT_KEYS,
    count: NEW_ACHIEVEMENT_KEYS.length,
  };
});

