/**
 * Unified Vehicle Registry - Single source of truth for all vehicle data.
 * Merges vehicles from the legacy VehicleRegistry and the bag system's AVAILABLE_VEHICLES.
 * 
 * This registry serves both UI (bag) and gameplay (vehicle manager/controller) layers
 * without diverging representations.
 */

// Legacy Vehicle Registry (from VehicleRegistry.js) - Inlined to remove dependency
const VEHICLE_REGISTRY = {
  // Rental/Purchase Vehicles (from VehicleSpriteSystem)
  vehicle_sports_car: {
    id: 'vehicle_sports_car',
    name: 'Sports Car',
    type: 'car',
    category: 'ground',
    speed: 1.5,
    agility: 0.7,
    durability: 0.8,
    cost: 1000,
    capacity: 2,
    special: 'boost',
    description: 'Fast sports car with high speed',
    baseSpeed: 420,
    maxSpeed: 420,
    acceleration: 1800,
    friction: 0.88,
    jumpForce: 900,
    interactionRadius: 70,
  },
  
  vehicle_hoverbike: {
    id: 'vehicle_hoverbike',
    name: 'Hoverbike',
    type: 'bike',
    category: 'hover',
    speed: 1.2,
    agility: 1.0,
    durability: 0.6,
    cost: 800,
    capacity: 1,
    special: 'agility',
    description: 'Agile hoverbike for quick movement',
    baseSpeed: 336,
    maxSpeed: 336,
    acceleration: 960,
    friction: 0.94,
    jumpForce: 720,
    interactionRadius: 70,
  },
  
  vehicle_hoverbike_alt: {
    id: 'vehicle_hoverbike_alt',
    name: 'Hoverbike Alt',
    type: 'bike',
    category: 'hover',
    speed: 1.1,
    agility: 0.9,
    durability: 0.7,
    cost: 750,
    capacity: 1,
    special: 'agility',
    description: 'Alternative hoverbike design',
    baseSpeed: 308,
    maxSpeed: 308,
    acceleration: 880,
    friction: 0.93,
    jumpForce: 690,
    interactionRadius: 70,
  },
  
  vehicle_jetcart: {
    id: 'vehicle_jetcart',
    name: 'Jet Cart',
    type: 'cart',
    category: 'ground',
    speed: 1.0,
    agility: 0.8,
    durability: 1.0,
    cost: 1200,
    capacity: 3,
    special: 'durability',
    description: 'Balanced jet-powered cart',
    baseSpeed: 280,
    maxSpeed: 280,
    acceleration: 800,
    friction: 0.95,
    jumpForce: 600,
    interactionRadius: 80,
  },
  
  vehicle_turbo_board: {
    id: 'vehicle_turbo_board',
    name: 'Turbo Board',
    type: 'board',
    category: 'hover',
    speed: 1.3,
    agility: 1.2,
    durability: 0.5,
    cost: 600,
    capacity: 1,
    special: 'speed',
    description: 'Lightweight turbo board',
    baseSpeed: 364,
    maxSpeed: 364,
    acceleration: 1000,
    friction: 0.92,
    jumpForce: 780,
    interactionRadius: 60,
  },
  
  // Traffic Vehicles (from TrafficSystem)
  traffic_sedan: {
    id: 'traffic_sedan',
    name: 'Sedan',
    type: 'sedan',
    category: 'ground',
    speed: 0.57,
    agility: 1.0,
    durability: 0.71,
    hp: 200,
    cost: 500,
    capacity: 2,
    special: 'civilian',
    description: 'Standard civilian sedan',
    baseSpeed: 160,
    maxSpeed: 160,
    acceleration: 200,
    friction: 0.95,
    handling: 1.0,
    interactionRadius: 70,
  },
  
  traffic_van: {
    id: 'traffic_van',
    name: 'Van',
    type: 'van',
    category: 'ground',
    speed: 0.46,
    agility: 0.8,
    durability: 1.07,
    hp: 300,
    cost: 800,
    capacity: 3,
    special: 'durability',
    description: 'Heavy utility van',
    baseSpeed: 130,
    maxSpeed: 130,
    acceleration: 160,
    friction: 0.96,
    handling: 0.8,
    interactionRadius: 80,
  },
  
  traffic_bike: {
    id: 'traffic_bike',
    name: 'Traffic Bike',
    type: 'bike',
    category: 'hover',
    speed: 0.71,
    agility: 1.2,
    durability: 0.43,
    hp: 120,
    cost: 400,
    capacity: 1,
    special: 'agility',
    description: 'Fast traffic motorcycle',
    baseSpeed: 200,
    maxSpeed: 200,
    acceleration: 260,
    friction: 0.93,
    handling: 1.2,
    interactionRadius: 60,
  },
  
  // Personal Rideable Vehicles (from vehicle-system.js)
  personal_bike: {
    id: 'personal_bike',
    name: 'Personal Bike',
    type: 'bike',
    category: 'ground',
    speed: 2.6,
    agility: 1.3,
    durability: 0.6,
    cost: 900,
    capacity: 2,
    special: 'speed + agility',
    description: 'Lightweight, fast, agile—used by default in mid-speed chase segments',
    baseSpeed: 728,
    maxSpeed: 728,
    acceleration: 1400,
    friction: 0.90,
    jumpForce: 800,
    interactionRadius: 65,
  },
  
  personal_chopper: {
    id: 'personal_chopper',
    name: 'Chopper',
    type: 'chopper',
    category: 'ground',
    speed: 2.0,
    agility: 0.7,
    durability: 1.2,
    cost: 1500,
    capacity: 3,
    special: 'durability + capacity',
    description: 'Heavy cruiser bike with multiple seats; strong stability, slower turns',
    baseSpeed: 560,
    maxSpeed: 560,
    acceleration: 700,
    friction: 0.88,
    jumpForce: 550,
    interactionRadius: 80,
  },
  
  personal_jetpack: {
    id: 'personal_jetpack',
    name: 'Jetpack',
    type: 'jetpack',
    category: 'air',
    speed: 2.4,
    agility: 1.5,
    durability: 0.4,
    cost: 2500,
    capacity: 1,
    special: 'flight + evasion',
    description: 'Personal flight pack; allows vertical freedom and evasion from hazards',
    baseSpeed: 672,
    maxSpeed: 672,
    acceleration: 1100,
    friction: 0.92,
    jumpForce: 1200,
    interactionRadius: 60,
    canFly: true,
  },
  
  personal_car: {
    id: 'personal_car',
    name: 'Personal Car',
    type: 'car',
    category: 'ground',
    speed: 2.2,
    agility: 1.0,
    durability: 0.9,
    cost: 1100,
    capacity: 3,
    special: 'balanced',
    description: 'Balanced baseline vehicle; used when no other type is specified',
    baseSpeed: 616,
    maxSpeed: 616,
    acceleration: 900,
    friction: 0.85,
    jumpForce: 650,
    interactionRadius: 75,
  },
  
  // Battle Mechs
  mech_proto: {
    id: 'mech_proto',
    name: 'Mech Proto',
    type: 'mech',
    category: 'ground',
    speed: 2.0,
    agility: 0.5,
    durability: 2.0,
    cost: 3000,
    capacity: 1,
    special: 'knockback immunity',
    description: 'Early-stage battle mech; high HP, heavy knockback immunity',
    baseSpeed: 560,
    maxSpeed: 560,
    acceleration: 600,
    friction: 0.85,
    jumpForce: 500,
    hp: 1000,
    interactionRadius: 90,
    hasKnockbackImmunity: true,
  },
  
  mech_apex: {
    id: 'mech_apex',
    name: 'Mech Apex',
    type: 'mech',
    category: 'ground',
    speed: 2.3,
    agility: 0.7,
    durability: 2.5,
    cost: 5000,
    capacity: 1,
    special: 'boost + missiles',
    description: 'Advanced version with shoulder cannons; V1 = Boost, V2 = Missile Barrage',
    baseSpeed: 644,
    maxSpeed: 644,
    acceleration: 750,
    friction: 0.83,
    jumpForce: 550,
    hp: 1500,
    interactionRadius: 95,
    hasKnockbackImmunity: true,
    hasWeapons: true,
    abilities: ['boost', 'missile_barrage'],
  },
  
  skateboard_street: {
    id: 'skateboard_street',
    name: 'Street Skateboard',
    type: 'skateboard',
    category: 'ground',
    speed: 2.5,
    agility: 1.4,
    durability: 0.3,
    cost: 500,
    capacity: 1,
    special: 'strong acceleration',
    description: 'Street-style board; strong acceleration, low control in air',
    baseSpeed: 700,
    maxSpeed: 700,
    acceleration: 1600,
    friction: 0.90,
    jumpForce: 700,
    interactionRadius: 55,
    lowAirControl: true,
  },
  
  // Public Transit (from TransportationSystem)
  transit_bus: {
    id: 'transit_bus',
    name: 'Bus',
    type: 'bus',
    category: 'ground',
    speed: 0.64,
    agility: 0.5,
    durability: 1.5,
    hp: 500,
    cost: 2000,
    capacity: 8,
    special: 'transport',
    description: 'Public bus for passengers',
    baseSpeed: 180,
    maxSpeed: 180,
    acceleration: 600,
    friction: 0.97,
    interval: 30,
    interactionRadius: 100,
  },
  
  transit_train: {
    id: 'transit_train',
    name: 'Train',
    type: 'train',
    category: 'ground',
    speed: 0.93,
    agility: 0.3,
    durability: 2.0,
    hp: 800,
    cost: 5000,
    capacity: 8,
    special: 'transport',
    description: 'High-speed train coach',
    baseSpeed: 260,
    maxSpeed: 260,
    acceleration: 700,
    friction: 0.98,
    interval: 60,
    interactionRadius: 120,
  },
};

/**
 * Curated list of vehicle definitions sourced from the bag system.
 * These entries intentionally mirror the player-facing catalog so the unified
 * registry can serve both UI (bag) and gameplay (vehicle manager/controller)
 * layers without diverging representations.
 */
const BAG_VEHICLE_SOURCE = [
  {
    id: "vehicle_bike",
    name: "Mountain Bike",
    icon: "🚴",
    type: "vehicle",
    rarity: "common",
    category: "ground",
    cost: 150,
    basePrice: 150,
    speed: 15,
    defense: 2,
    hp: 30,
    effects: [{ name: "Endurance", desc: "+15% stamina recovery", value: 15 }],
    abilities: ["Pedal Boost"],
    description: "Fast and reliable transport",
    lore: "Eco-friendly mountain cruiser",
    levelReq: 1,
    tags: ["transport", "eco", "common"],
    fuelType: "stamina",
    capacity: 1,
  },
  {
    id: "vehicle_scooter",
    name: "Electric Scooter",
    icon: "🛴",
    type: "vehicle",
    rarity: "common",
    category: "ground",
    cost: 150,
    basePrice: 150,
    speed: 18,
    defense: 1,
    hp: 25,
    effects: [{ name: "Electric Boost", desc: "+10% speed in cities", value: 10 }],
    abilities: ["Quick Start"],
    description: "Eco-friendly ride",
    lore: "Battery-powered convenience",
    levelReq: 1,
    tags: ["electric", "urban", "fast"],
    fuelType: "battery",
    capacity: 1,
  },
  {
    id: "vehicle_skateboard",
    name: "Skateboard",
    icon: "🛹",
    type: "vehicle",
    rarity: "common",
    category: "ground",
    cost: 100,
    basePrice: 100,
    speed: 12,
    defense: 0,
    hp: 15,
    effects: [{ name: "Tricks", desc: "+20% evasion while moving", value: 20 }],
    abilities: ["Grind"],
    description: "Cool street cruiser",
    lore: "Street culture icon",
    levelReq: 1,
    tags: ["street", "tricks", "agile"],
    fuelType: "none",
    capacity: 1,
  },
  {
    id: "vehicle_car",
    name: "Compact Car",
    icon: "🚗",
    type: "vehicle",
    rarity: "common",
    category: "ground",
    cost: 200,
    basePrice: 200,
    speed: 25,
    defense: 5,
    hp: 60,
    effects: [{ name: "Comfort", desc: "Restore 5 HP/sec while driving", value: 5 }],
    abilities: ["Auto Drive"],
    description: "Comfortable daily driver",
    lore: "Reliable city car",
    levelReq: 1,
    tags: ["car", "comfort", "safe"],
    fuelType: "gas",
    capacity: 4,
  },
  {
    id: "vehicle_bus",
    name: "Tour Bus",
    icon: "🚌",
    type: "vehicle",
    rarity: "common",
    category: "ground",
    cost: 180,
    basePrice: 180,
    speed: 20,
    defense: 8,
    hp: 100,
    effects: [{ name: "Group Travel", desc: "Entire party gains +10% XP", value: 10 }],
    abilities: ["Mass Transit"],
    description: "Carries the whole party",
    lore: "Room for everyone",
    levelReq: 1,
    tags: ["transport", "party", "large"],
    fuelType: "diesel",
    capacity: 12,
  },
  {
    id: "vehicle_motorcycle",
    name: "Motorcycle",
    icon: "🏍️",
    type: "vehicle",
    rarity: "common",
    category: "ground",
    cost: 220,
    basePrice: 220,
    speed: 30,
    defense: 3,
    hp: 40,
    effects: [{ name: "Speed Demon", desc: "+25% max speed", value: 25 }],
    abilities: ["Wheelie"],
    description: "Fast two-wheeler",
    lore: "Built for speed",
    levelReq: 1,
    tags: ["bike", "speed", "dangerous"],
    fuelType: "gas",
    capacity: 2,
  },
  {
    id: "vehicle_tricycle",
    name: "Tricycle",
    icon: "🚲",
    type: "vehicle",
    rarity: "common",
    category: "ground",
    cost: 80,
    basePrice: 80,
    speed: 8,
    defense: 2,
    hp: 20,
    effects: [{ name: "Stable", desc: "Cannot be knocked off", value: 100 }],
    abilities: ["Balance"],
    description: "Safe and steady",
    lore: "Training wheels optional",
    levelReq: 1,
    tags: ["safe", "beginner", "stable"],
    fuelType: "none",
    capacity: 1,
  },
  {
    id: "vehicle_boat",
    name: "Rowboat",
    icon: "🚣",
    type: "vehicle",
    rarity: "common",
    category: "water",
    cost: 160,
    basePrice: 160,
    speed: 10,
    defense: 4,
    hp: 50,
    effects: [{ name: "Water Travel", desc: "Can traverse water", value: 100 }],
    abilities: ["Row"],
    description: "Water transport",
    lore: "For rivers and lakes",
    levelReq: 1,
    tags: ["water", "boat", "manual"],
    fuelType: "none",
    capacity: 2,
  },
  {
    id: "vehicle_cart",
    name: "Wooden Cart",
    icon: "🛒",
    type: "vehicle",
    rarity: "common",
    category: "ground",
    cost: 120,
    basePrice: 120,
    speed: 6,
    defense: 3,
    hp: 40,
    effects: [{ name: "Cargo Space", desc: "+20 inventory slots", value: 20 }],
    abilities: ["Haul"],
    description: "Carry more items",
    lore: "Simple storage solution",
    levelReq: 1,
    tags: ["storage", "utility", "slow"],
    fuelType: "none",
    capacity: 1,
  },
  {
    id: "vehicle_segway",
    name: "Segway",
    icon: "🛴",
    type: "vehicle",
    rarity: "common",
    category: "ground",
    cost: 140,
    basePrice: 140,
    speed: 14,
    defense: 1,
    hp: 20,
    effects: [{ name: "Self-Balancing", desc: "+15% stability", value: 15 }],
    abilities: ["Cruise"],
    description: "Personal transporter",
    lore: "Tech meets convenience",
    levelReq: 1,
    tags: ["tech", "balance", "urban"],
    fuelType: "battery",
    capacity: 1,
  },
  {
    id: "vehicle_wagon",
    name: "Horse Wagon",
    icon: "🐴",
    type: "vehicle",
    rarity: "common",
    category: "ground",
    cost: 250,
    basePrice: 250,
    speed: 12,
    defense: 6,
    hp: 80,
    effects: [{ name: "Beast Power", desc: "Horse provides +10 defense", value: 10 }],
    abilities: ["Gallop"],
    description: "Classic transport",
    lore: "Trusty steed included",
    levelReq: 1,
    tags: ["classic", "beast", "sturdy"],
    fuelType: "food",
    capacity: 4,
  },
  {
    id: "vehicle_raft",
    name: "Log Raft",
    icon: "🪵",
    type: "vehicle",
    rarity: "common",
    category: "water",
    cost: 90,
    basePrice: 90,
    speed: 5,
    defense: 2,
    hp: 35,
    effects: [{ name: "Floats", desc: "Never sink in water", value: 100 }],
    abilities: ["Float"],
    description: "Basic water craft",
    lore: "Simple but effective",
    levelReq: 1,
    tags: ["water", "basic", "safe"],
    fuelType: "none",
    capacity: 2,
  },
  {
    id: "vehicle_sports_car",
    name: "Sports Car",
    icon: "🏎️",
    type: "vehicle",
    rarity: "uncommon",
    category: "ground",
    cost: 800,
    basePrice: 800,
    speed: 45,
    defense: 8,
    hp: 90,
    armor: 15,
    effects: [
      { name: "Nitro Boost", desc: "+50% speed for 10s (30s CD)", value: 50 },
      { name: "Aerodynamic", desc: "+20% fuel efficiency", value: 20 },
    ],
    abilities: ["Nitro", "Drift"],
    description: "High-performance racing machine",
    lore: "Built for speed",
    levelReq: 10,
    tags: ["racing", "fast", "luxury"],
    fuelType: "premium",
    capacity: 2,
  },
  {
    id: "vehicle_suv",
    name: "Off-Road SUV",
    icon: "🚙",
    type: "vehicle",
    rarity: "uncommon",
    category: "ground",
    cost: 900,
    basePrice: 900,
    speed: 35,
    defense: 15,
    hp: 150,
    armor: 25,
    effects: [
      { name: "All-Terrain", desc: "No speed penalty on rough terrain", value: 100 },
      { name: "Reinforced", desc: "+30% damage reduction", value: 30 },
    ],
    abilities: ["4WD", "Climb"],
    description: "Rugged all-terrain vehicle",
    lore: "Goes anywhere",
    levelReq: 12,
    tags: ["offroad", "tough", "versatile"],
    fuelType: "gas",
    capacity: 5,
  },
  {
    id: "vehicle_jet_ski",
    name: "Jet Ski",
    icon: "🚤",
    type: "vehicle",
    rarity: "uncommon",
    category: "water",
    cost: 750,
    basePrice: 750,
    speed: 50,
    defense: 5,
    hp: 60,
    armor: 10,
    effects: [
      { name: "Water Speed", desc: "+100% speed on water", value: 100 },
      { name: "Wave Jump", desc: "Can jump over obstacles", value: 100 },
    ],
    abilities: ["Turbo", "Jump"],
    description: "Fast water vehicle",
    lore: "King of the waves",
    levelReq: 11,
    tags: ["water", "speed", "fun"],
    fuelType: "gas",
    capacity: 2,
  },
  {
    id: "vehicle_helicopter",
    name: "Light Helicopter",
    icon: "🚁",
    type: "vehicle",
    rarity: "uncommon",
    category: "air",
    cost: 1200,
    basePrice: 1200,
    speed: 40,
    defense: 10,
    hp: 120,
    armor: 20,
    effects: [
      { name: "Flight", desc: "Can fly over terrain", value: 100 },
      { name: "Aerial View", desc: "+30% detection range", value: 30 },
    ],
    abilities: ["Fly", "Hover"],
    description: "Versatile aerial transport",
    lore: "Take to the skies",
    levelReq: 15,
    tags: ["air", "flight", "versatile"],
    fuelType: "aviation",
    capacity: 4,
  },
  {
    id: "vehicle_tank",
    name: "Light Tank",
    icon: "🚜",
    type: "vehicle",
    rarity: "uncommon",
    category: "ground",
    cost: 1100,
    basePrice: 1100,
    speed: 18,
    defense: 30,
    hp: 250,
    armor: 50,
    effects: [
      { name: "Armored", desc: "+50% damage reduction", value: 50 },
      { name: "Ramming", desc: "Deal 100 damage on collision", value: 100 },
    ],
    abilities: ["Ram", "Shell Fire"],
    description: "Heavy armored vehicle",
    lore: "Unstoppable force",
    levelReq: 18,
    tags: ["tank", "armor", "combat"],
    fuelType: "diesel",
    capacity: 3,
  },
  {
    id: "vehicle_speedboat",
    name: "Speedboat",
    icon: "⛵",
    type: "vehicle",
    rarity: "uncommon",
    category: "water",
    cost: 850,
    basePrice: 850,
    speed: 48,
    defense: 6,
    hp: 70,
    armor: 12,
    effects: [
      { name: "Hydroplane", desc: "+60% water speed", value: 60 },
      { name: "Spray", desc: "Enemies behind are slowed 20%", value: 20 },
    ],
    abilities: ["Boost", "Sharp Turn"],
    description: "Racing watercraft",
    lore: "Speed on waves",
    levelReq: 13,
    tags: ["water", "racing", "agile"],
    fuelType: "gas",
    capacity: 4,
  },
  {
    id: "vehicle_atv",
    name: "ATV Quad",
    icon: "🏜️",
    type: "vehicle",
    rarity: "uncommon",
    category: "ground",
    cost: 700,
    basePrice: 700,
    speed: 32,
    defense: 10,
    hp: 90,
    armor: 18,
    effects: [
      { name: "Rough Rider", desc: "+40% speed on dirt", value: 40 },
      { name: "Sturdy", desc: "+25% HP", value: 25 },
    ],
    abilities: ["Power Slide", "Jump"],
    description: "All-terrain quad bike",
    lore: "Desert dominator",
    levelReq: 12,
    tags: ["offroad", "quad", "fun"],
    fuelType: "gas",
    capacity: 1,
  },
  {
    id: "vehicle_glider",
    name: "Hang Glider",
    icon: "🪂",
    type: "vehicle",
    rarity: "uncommon",
    category: "air",
    cost: 650,
    basePrice: 650,
    speed: 28,
    defense: 2,
    hp: 30,
    armor: 5,
    effects: [
      { name: "Glide", desc: "Silent movement, +35% stealth", value: 35 },
      { name: "Updraft", desc: "Gain altitude near heat sources", value: 100 },
    ],
    abilities: ["Soar", "Land"],
    description: "Silent aerial glider",
    lore: "Ride the wind",
    levelReq: 10,
    tags: ["air", "stealth", "glide"],
    fuelType: "wind",
    capacity: 1,
  },
  {
    id: "vehicle_snowmobile",
    name: "Snowmobile",
    icon: "🛷",
    type: "vehicle",
    rarity: "uncommon",
    category: "ground",
    cost: 780,
    basePrice: 780,
    speed: 35,
    defense: 8,
    hp: 75,
    armor: 15,
    effects: [
      { name: "Ice Travel", desc: "+80% speed on snow/ice", value: 80 },
      { name: "Cold Resistance", desc: "Immune to frost damage", value: 100 },
    ],
    abilities: ["Drift", "Boost"],
    description: "Winter terrain specialist",
    lore: "Master of ice",
    levelReq: 14,
    tags: ["snow", "ice", "fast"],
    fuelType: "gas",
    capacity: 2,
  },
  {
    id: "vehicle_tractor",
    name: "Farm Tractor",
    icon: "🚜",
    type: "vehicle",
    rarity: "uncommon",
    category: "ground",
    cost: 950,
    basePrice: 950,
    speed: 15,
    defense: 20,
    hp: 180,
    armor: 35,
    effects: [
      { name: "Tow Power", desc: "Can pull heavy loads", value: 100 },
      { name: "Work Horse", desc: "+40 inventory slots", value: 40 },
    ],
    abilities: ["Pull", "Till"],
    description: "Heavy-duty workhorse",
    lore: "Farm life essential",
    levelReq: 15,
    tags: ["utility", "strong", "slow"],
    fuelType: "diesel",
    capacity: 2,
  },
  {
    id: "vehicle_drone",
    name: "Cargo Drone",
    icon: "🛸",
    type: "vehicle",
    rarity: "uncommon",
    category: "hover",
    cost: 1000,
    basePrice: 1000,
    speed: 38,
    defense: 5,
    hp: 50,
    armor: 10,
    effects: [
      { name: "Auto-Pilot", desc: "Can travel while AFK", value: 100 },
      { name: "Hover", desc: "Ignore ground-based obstacles", value: 100 },
    ],
    abilities: ["Hover", "Deliver"],
    description: "Autonomous flying cargo",
    lore: "Future of delivery",
    levelReq: 16,
    tags: ["tech", "auto", "flying"],
    fuelType: "battery",
    capacity: 0,
  },
  {
    id: "vehicle_segway_pro",
    name: "Segway Pro",
    icon: "🛴",
    type: "vehicle",
    rarity: "uncommon",
    category: "ground",
    cost: 680,
    basePrice: 680,
    speed: 22,
    defense: 4,
    hp: 45,
    armor: 8,
    effects: [
      { name: "Gyro Stabilizer", desc: "Cannot be pushed/knocked back", value: 100 },
      { name: "Smart Balance", desc: "+18% control", value: 18 },
    ],
    abilities: ["Auto-Balance", "Cruise Control"],
    description: "Advanced personal transport",
    lore: "Balance perfected",
    levelReq: 11,
    tags: ["tech", "stable", "urban"],
    fuelType: "battery",
    capacity: 1,
  },
  {
    id: "vehicle_supercar",
    name: "Supercar",
    icon: "🏎️",
    type: "vehicle",
    rarity: "rare",
    category: "ground",
    cost: 3500,
    basePrice: 3500,
    speed: 70,
    defense: 12,
    hp: 140,
    armor: 25,
    effects: [
      { name: "Twin Turbo", desc: "+100% acceleration", value: 100 },
      { name: "Luxury", desc: "+20% all stats while driving", value: 20 },
      { name: "Nitrous Oxide", desc: "Temporary invincibility during boost", value: 100 },
    ],
    abilities: ["Nitro Boost", "Launch Control", "Drift"],
    description: "Ultimate racing machine",
    lore: "Engineering perfection",
    levelReq: 30,
    tags: ["racing", "luxury", "ultimate"],
    fuelType: "racing",
    capacity: 2,
  },
  {
    id: "vehicle_combat_bike",
    name: "Combat Bike",
    icon: "🏍️",
    type: "vehicle",
    rarity: "rare",
    category: "ground",
    cost: 3200,
    basePrice: 3200,
    speed: 65,
    defense: 18,
    hp: 120,
    armor: 30,
    effects: [
      { name: "Mounted Guns", desc: "Fire weapons while driving (50 dmg)", value: 50 },
      { name: "Reinforced Frame", desc: "+35% defense", value: 35 },
      { name: "Tactical Boost", desc: "Leave smoke trail (enemies slowed 30%)", value: 30 },
    ],
    abilities: ["Drive-By", "Smoke Screen", "Ram"],
    description: "Weaponized motorcycle",
    lore: "War machine on wheels",
    levelReq: 28,
    tags: ["combat", "weapons", "fast"],
    fuelType: "military",
    capacity: 2,
  },
  {
    id: "vehicle_yacht",
    name: "Luxury Yacht",
    icon: "🛥️",
    type: "vehicle",
    rarity: "rare",
    category: "water",
    cost: 4000,
    basePrice: 4000,
    speed: 30,
    defense: 20,
    hp: 300,
    armor: 40,
    effects: [
      { name: "Mobile Base", desc: "Full HP/MP regen while aboard", value: 100 },
      { name: "Party Boat", desc: "All allies gain +25% stats", value: 25 },
      { name: "Deep Sea", desc: "Can access ocean areas", value: 100 },
    ],
    abilities: ["Cruise", "Anchor", "Sonar"],
    description: "Floating luxury home",
    lore: "Live on the ocean",
    levelReq: 32,
    tags: ["water", "luxury", "base"],
    fuelType: "diesel",
    capacity: 12,
  },
  {
    id: "vehicle_gunship",
    name: "Attack Helicopter",
    icon: "🚁",
    type: "vehicle",
    rarity: "rare",
    category: "air",
    cost: 4200,
    basePrice: 4200,
    speed: 55,
    defense: 25,
    hp: 200,
    armor: 45,
    effects: [
      { name: "Airborne Arsenal", desc: "Fire missiles (150 AOE damage)", value: 150 },
      { name: "Tactical Support", desc: "Allies gain +30% damage", value: 30 },
      { name: "Evasive Maneuvers", desc: "+40% dodge vs projectiles", value: 40 },
    ],
    abilities: ["Missile Strike", "Minigun", "Strafe"],
    description: "Military attack chopper",
    lore: "Air superiority",
    levelReq: 35,
    tags: ["military", "combat", "air"],
    fuelType: "aviation",
    capacity: 4,
  },
  {
    id: "vehicle_mech_walker",
    name: "Mech Walker",
    icon: "🤖",
    type: "vehicle",
    rarity: "rare",
    category: "mech",
    cost: 3800,
    basePrice: 3800,
    speed: 28,
    defense: 40,
    hp: 350,
    armor: 60,
    effects: [
      { name: "Powered Armor", desc: "+50 defense, +100 HP", value: 50 },
      { name: "Stomp Attack", desc: "Each step deals 80 AOE damage", value: 80 },
      { name: "Shield Generator", desc: "Absorb 200 damage before taking HP loss", value: 200 },
    ],
    abilities: ["Stomp", "Laser", "Shield"],
    description: "Bipedal combat mech",
    lore: "Walking fortress",
    levelReq: 33,
    tags: ["mech", "combat", "tech"],
    fuelType: "power cell",
    capacity: 1,
  },
  {
    id: "vehicle_hoverboard",
    name: "Quantum Hoverboard",
    icon: "🛹",
    type: "vehicle",
    rarity: "rare",
    category: "hover",
    cost: 3300,
    basePrice: 3300,
    speed: 60,
    defense: 10,
    hp: 80,
    armor: 15,
    effects: [
      { name: "Anti-Gravity", desc: "Hover over all terrain types", value: 100 },
      { name: "Quantum Dash", desc: "Short teleport forward (5s CD)", value: 100 },
      { name: "Friction-less", desc: "+45% max speed, never slow down", value: 45 },
    ],
    abilities: ["Hover", "Quantum Dash", "Grind"],
    description: "Future skateboard tech",
    lore: "Defies gravity",
    levelReq: 31,
    tags: ["tech", "hover", "fast"],
    fuelType: "quantum",
    capacity: 1,
  },
  {
    id: "vehicle_submarine",
    name: "Submarine",
    icon: "🚢",
    type: "vehicle",
    rarity: "rare",
    category: "water",
    cost: 3600,
    basePrice: 3600,
    speed: 25,
    defense: 35,
    hp: 280,
    armor: 55,
    effects: [
      { name: "Deep Dive", desc: "Access underwater areas", value: 100 },
      { name: "Torpedo Bay", desc: "Fire torpedoes (120 damage)", value: 120 },
      { name: "Sonar Ping", desc: "Reveal all nearby enemies", value: 100 },
    ],
    abilities: ["Dive", "Torpedo", "Sonar"],
    description: "Deep sea explorer",
    lore: "Master the abyss",
    levelReq: 32,
    tags: ["water", "deep", "combat"],
    fuelType: "nuclear",
    capacity: 6,
  },
  {
    id: "vehicle_monster_truck",
    name: "Monster Truck",
    icon: "🚚",
    type: "vehicle",
    rarity: "rare",
    category: "ground",
    cost: 3400,
    basePrice: 3400,
    speed: 32,
    defense: 28,
    hp: 220,
    armor: 48,
    effects: [
      { name: "Crush", desc: "Drive over small obstacles/enemies", value: 100 },
      { name: "Giant Tires", desc: "+40% HP, +35% defense", value: 40 },
      { name: "Shockwave", desc: "Landing creates AOE stun", value: 100 },
    ],
    abilities: ["Jump", "Crush", "Roar"],
    description: "Massive off-road beast",
    lore: "Nothing stops this",
    levelReq: 30,
    tags: ["massive", "offroad", "power"],
    fuelType: "diesel",
    capacity: 2,
  },
  {
    id: "vehicle_hypersonic_jet",
    name: "Hypersonic Jet",
    icon: "✈️",
    type: "vehicle",
    rarity: "epic",
    category: "air",
    cost: 12000,
    basePrice: 12000,
    speed: 120,
    defense: 35,
    hp: 350,
    armor: 50,
    effects: [
      { name: "Mach 5", desc: "+200% speed, break sound barrier", value: 200 },
      { name: "Afterburner", desc: "Leave fire trail (100 damage/sec)", value: 100 },
      { name: "Missile System", desc: "Auto-fire missiles (200 damage)", value: 200 },
      { name: "Stealth Mode", desc: "Invisible to radar", value: 100 },
      { name: "Ejection Seat", desc: "Survive any crash at 1 HP", value: 100 },
    ],
    abilities: ["Supersonic Flight", "Air-to-Air Missiles", "Barrel Roll", "Eject"],
    description: "Fastest aircraft ever built",
    lore: "Breaks all speed records",
    levelReq: 50,
    tags: ["air", "military", "ultimate"],
    fuelType: "jet fuel",
    capacity: 2,
  },
  {
    id: "vehicle_battle_tank",
    name: "Battle Tank MK-X",
    icon: "🎖️",
    type: "vehicle",
    rarity: "epic",
    category: "ground",
    cost: 11000,
    basePrice: 11000,
    speed: 25,
    defense: 80,
    hp: 600,
    armor: 100,
    effects: [
      { name: "Main Cannon", desc: "Fire 300 damage shells (8s CD)", value: 300 },
      { name: "Reactive Armor", desc: "Block 500 damage, then regenerate", value: 500 },
      { name: "Siege Mode", desc: "+100% damage, -50% speed", value: 100 },
      { name: "Unstoppable", desc: "Immune to CC, crush obstacles", value: 100 },
      { name: "Crew Bonus", desc: "Allies inside gain +40% all stats", value: 40 },
    ],
    abilities: ["Main Cannon", "Machine Gun", "Siege Mode", "Emergency Repair"],
    description: "Ultimate ground war machine",
    lore: "Dominates battlefields",
    levelReq: 52,
    tags: ["tank", "military", "destruction"],
    fuelType: "military",
    capacity: 4,
  },
  {
    id: "vehicle_mecha_titan",
    name: "Titan Mecha",
    icon: "🤖",
    type: "vehicle",
    rarity: "epic",
    category: "mech",
    cost: 13000,
    basePrice: 13000,
    speed: 40,
    defense: 70,
    hp: 800,
    armor: 120,
    effects: [
      { name: "Titan Form", desc: "+150% size, intimidate enemies", value: 150 },
      { name: "Plasma Cannons", desc: "Dual cannons (250 damage each)", value: 250 },
      { name: "Force Field", desc: "Absorb 600 damage shield", value: 600 },
      { name: "Rocket Boosters", desc: "Jump 100m, slam for 400 damage", value: 400 },
      { name: "AI Co-Pilot", desc: "Auto-dodge, +50% accuracy", value: 50 },
    ],
    abilities: ["Plasma Barrage", "Rocket Jump", "Melee Smash", "Shield"],
    description: "Giant piloted mecha",
    lore: "Titan of war",
    levelReq: 55,
    tags: ["mech", "giant", "powerful"],
    fuelType: "fusion",
    capacity: 1,
  },
  {
    id: "vehicle_spaceship",
    name: "Star Cruiser",
    icon: "🚀",
    type: "vehicle",
    rarity: "epic",
    category: "space",
    cost: 14000,
    basePrice: 14000,
    speed: 100,
    defense: 50,
    hp: 500,
    armor: 80,
    effects: [
      { name: "Space Travel", desc: "Access space zones", value: 100 },
      { name: "Warp Drive", desc: "Instant travel to any location", value: 100 },
      { name: "Laser Batteries", desc: "Fire 8 lasers (180 damage each)", value: 180 },
      { name: "Life Support", desc: "Infinite HP regen in ship", value: 9999 },
      { name: "Tractor Beam", desc: "Pull enemies (200 damage)", value: 200 },
    ],
    abilities: ["Warp", "Laser Barrage", "Shields", "Tractor Beam"],
    description: "Interstellar vessel",
    lore: "Explore the cosmos",
    levelReq: 58,
    tags: ["space", "sci-fi", "exploration"],
    fuelType: "antimatter",
    capacity: 20,
  },
  {
    id: "vehicle_time_machine",
    name: "Chrono-Mobile",
    icon: "⏰",
    type: "vehicle",
    rarity: "epic",
    category: "space",
    cost: 15000,
    basePrice: 15000,
    speed: 88,
    defense: 45,
    hp: 400,
    armor: 70,
    effects: [
      { name: "Time Travel", desc: "Rewind 30 seconds on death", value: 30 },
      { name: "Temporal Shield", desc: "Negate next 3 hits", value: 3 },
      { name: "Flux Capacitor", desc: "+88% speed (reference achieved)", value: 88 },
      { name: "Paradox Engine", desc: "Exist in 2 places at once", value: 2 },
      { name: "Time Stop", desc: "Freeze enemies for 5s (60s CD)", value: 5 },
    ],
    abilities: ["Time Warp", "Freeze Time", "Paradox Clone", "Rewind"],
    description: "Breaks the laws of physics",
    lore: "When this baby hits 88mph...",
    levelReq: 60,
    tags: ["time", "legendary", "sci-fi"],
    fuelType: "temporal",
    capacity: 2,
  },
  {
    id: "vehicle_god_chariot",
    name: "Divine Chariot",
    icon: "🐎",
    type: "vehicle",
    rarity: "legendary",
    category: "air",
    cost: 30000,
    basePrice: 30000,
    speed: 150,
    defense: 100,
    hp: 1200,
    armor: 150,
    effects: [
      { name: "Divine Speed", desc: "+500% speed, leave golden trail", value: 500 },
      { name: "Holy Protection", desc: "Immune to all damage", value: 100 },
      { name: "Celestial Flames", desc: "Enemies touched take 500 holy damage", value: 500 },
      { name: "Heaven's Blessing", desc: "Allies gain +100% all stats", value: 100 },
      { name: "Resurrection", desc: "Auto-revive at chariot location", value: 100 },
      { name: "Sky Walk", desc: "Drive on air, water, or land", value: 100 },
    ],
    abilities: ["Divine Charge", "Holy Nova", "Blessing Aura", "Revive"],
    description: "Chariot of the gods",
    lore: "Driven by angels",
    levelReq: 80,
    tags: ["divine", "legendary", "ultimate"],
    fuelType: "faith",
    capacity: 4,
  },
  {
    id: "vehicle_world_eater",
    name: "World Eater Titan",
    icon: "🦾",
    type: "vehicle",
    rarity: "legendary",
    category: "mech",
    cost: 35000,
    basePrice: 35000,
    speed: 30,
    defense: 200,
    hp: 2000,
    armor: 300,
    effects: [
      { name: "Titan Scale", desc: "1000% size, crush everything", value: 1000 },
      { name: "Devastation", desc: "Every step deals 1000 AOE damage", value: 1000 },
      { name: "Impenetrable", desc: "Take 90% reduced damage", value: 90 },
      { name: "World Breaker", desc: "Destroy terrain, create paths", value: 100 },
      { name: "Fear Aura", desc: "Enemies flee in terror", value: 100 },
      { name: "Regeneration Core", desc: "Heal 50 HP/sec", value: 50 },
    ],
    abilities: ["Devastation Wave", "Titan Stomp", "Roar", "Regenerate"],
    description: "Colossus that devours worlds",
    lore: "When it walks, worlds tremble",
    levelReq: 85,
    tags: ["titan", "colossal", "destruction"],
    fuelType: "worlds",
    capacity: 1,
  },
  {
    id: "vehicle_dimensional_rift",
    name: "Rift Walker",
    icon: "🌀",
    type: "vehicle",
    rarity: "legendary",
    category: "space",
    cost: 40000,
    basePrice: 40000,
    speed: 200,
    defense: 120,
    hp: 1500,
    armor: 180,
    effects: [
      { name: "Dimension Hop", desc: "Teleport anywhere instantly", value: 100 },
      { name: "Multi-Dimensional", desc: "Exist in all dimensions simultaneously", value: 100 },
      { name: "Void Engine", desc: "Ignore all obstacles/barriers", value: 100 },
      { name: "Reality Tear", desc: "Attacks pierce reality (800 true damage)", value: 800 },
      { name: "Time Dilation", desc: "Move 10× faster than everything", value: 1000 },
      { name: "Infinite Fuel", desc: "Never need to refuel", value: 9999 },
    ],
    abilities: ["Dimension Shift", "Void Blast", "Time Warp", "Reality Break"],
    description: "Vehicle that transcends space-time",
    lore: "Exists beyond comprehension",
    levelReq: 99,
    tags: ["dimensional", "ultimate", "transcendent"],
    fuelType: "infinity",
    capacity: 8,
  },
];

/**
 * Tunable presets allow the physics heuristics to remain predictable per category.
 * The numbers act as anchors so designers can tweak future additions quickly.
 */
const CATEGORY_PRESETS = {
  ground: { speedOffset: 180, speedMultiplier: 6, baseJump: 620, frictionBase: 0.9 },
  hover: { speedOffset: 190, speedMultiplier: 6.5, baseJump: 700, frictionBase: 0.88 },
  air: { speedOffset: 210, speedMultiplier: 7, baseJump: 820, frictionBase: 0.86 },
  water: { speedOffset: 160, speedMultiplier: 5.5, baseJump: 460, frictionBase: 0.94 },
  mech: { speedOffset: 170, speedMultiplier: 5, baseJump: 540, frictionBase: 0.92 },
  space: { speedOffset: 230, speedMultiplier: 7.5, baseJump: 880, frictionBase: 0.84 },
};

/**
 * Estimates agility from the catalog numbers so legacy bag entries follow the
 * same scale as the existing vehicle registry.
 */
function deriveAgility(vehicle) {
  if (typeof vehicle.agility === "number") {
    return vehicle.agility;
  }
  const speedScore = vehicle.speed ?? 20;
  const normalized = Math.min(Math.max(speedScore / 45, 0.4), 2.8);
  return Number(normalized.toFixed(2));
}

/**
 * Estimates durability using defense/armor/HP so tanky rides do not feel flimsy
 * when the physics layer reads their stats.
 */
function deriveDurability(vehicle) {
  if (typeof vehicle.durability === "number") {
    return vehicle.durability;
  }
  const defenseScore =
    (vehicle.defense ?? 0) +
    (vehicle.armor ?? 0) * 0.6 +
    (vehicle.hp ?? 0) / 80;
  const normalized = Math.min(Math.max(defenseScore / 20, 0.4), 3);
  return Number(normalized.toFixed(2));
}

/**
 * Builds out the missing physics fields so the controller has enough data to
 * simulate movement, even for vehicles that originally existed only in the bag.
 */
function derivePhysics(vehicle, categoryPreset, agility, durability) {
  const speedScore = vehicle.speed ?? 20;
  const baseSpeed = Math.round(
    categoryPreset.speedOffset + speedScore * categoryPreset.speedMultiplier
  );
  const maxSpeed = Math.round(baseSpeed * (1 + agility * 0.22));
  const acceleration = Math.round(speedScore * 8 + agility * 420);
  const friction = Number(
    Math.min(
      0.98,
      Math.max(
        0.78,
        categoryPreset.frictionBase - agility * 0.015 + durability * 0.01
      )
    ).toFixed(2)
  );
  const jumpForce = Math.round(categoryPreset.baseJump + agility * 110);
  const interactionRadius = Math.round(
    60 + (vehicle.capacity ?? 1) * 8 + durability * 12
  );

  return {
    baseSpeed,
    maxSpeed,
    acceleration,
    friction,
    jumpForce,
    interactionRadius,
  };
}

/**
 * Create a shallow clone of the legacy registry so we never mutate imported data.
 */
const unifiedRegistry = Object.keys(VEHICLE_REGISTRY).reduce(
  (acc, id) => {
    acc[id] = { ...VEHICLE_REGISTRY[id], source: "legacyRegistry" };
    return acc;
  },
  {}
);

for (const bagVehicle of BAG_VEHICLE_SOURCE) {
  const category = bagVehicle.category ?? "ground";
  const preset = CATEGORY_PRESETS[category] ?? CATEGORY_PRESETS.ground;
  const agility = deriveAgility(bagVehicle);
  const durability = deriveDurability(bagVehicle);
  const physics = derivePhysics(bagVehicle, preset, agility, durability);
  const existing = unifiedRegistry[bagVehicle.id];

  unifiedRegistry[bagVehicle.id] = {
    ...(existing ?? {}),
    ...bagVehicle,
    category: existing?.category ?? bagVehicle.category ?? "ground",
    agility: existing?.agility ?? bagVehicle.agility ?? agility,
    durability: existing?.durability ?? bagVehicle.durability ?? durability,
    baseSpeed: existing?.baseSpeed ?? physics.baseSpeed,
    maxSpeed: existing?.maxSpeed ?? physics.maxSpeed,
    acceleration: existing?.acceleration ?? physics.acceleration,
    friction: existing?.friction ?? physics.friction,
    jumpForce: existing?.jumpForce ?? physics.jumpForce,
    interactionRadius:
      existing?.interactionRadius ?? physics.interactionRadius,
    source: existing?.source ?? "bagSystem",
  };
}

export const UNIFIED_VEHICLE_REGISTRY = unifiedRegistry;

export function getUnifiedVehicle(id) {
  return UNIFIED_VEHICLE_REGISTRY[id] ?? null;
}

export function getAllUnifiedVehicles() {
  return Object.values(UNIFIED_VEHICLE_REGISTRY);
}


