import { build } from "esbuild";
import { promises as fs } from "fs";
import path from "path";
import { fileURLToPath } from "url";

// Resolve project root so the script works no matter where it's executed from.
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, "..");
const offlineDir = path.join(projectRoot, "offline");
const entryFile = path.join(projectRoot, "src", "game", "main.js");
const outputFile = path.join(offlineDir, "app.js");

async function ensureOfflineDir() {
  // Clean out any previous build to avoid serving stale assets.
  await fs.rm(offlineDir, { recursive: true, force: true });
  await fs.mkdir(offlineDir, { recursive: true });
}

async function bundleGame() {
  await build({
    entryPoints: [entryFile],
    bundle: true,
    minify: true,
    outfile: outputFile,
    format: "iife",
    target: ["es2018"],
    globalName: "VehicleDemo",
    logLevel: "info",
    loader: {
      ".js": "js",
    },
    banner: {
      js: "/* Offline bundle generated by build-offline.js */",
    },
  });
}

async function createOfflineHtml() {
  const indexPath = path.join(projectRoot, "index.html");
  const html = await fs.readFile(indexPath, "utf8");
  const scriptTagRegex = /<script\s+type="module"\s+src="src\/game\/main.js"><\/script>/i;
  const offlineHtml = html.replace(
    scriptTagRegex,
    '<script src="./app.js"></script>'
  );

  if (offlineHtml === html) {
    throw new Error(
      "Failed to patch index.html: could not locate module script tag."
    );
  }

  await fs.writeFile(path.join(offlineDir, "index.html"), offlineHtml, "utf8");
}

async function main() {
  console.log("\n[Offline Build] Bundling for file:// usage...");
  await ensureOfflineDir();
  await bundleGame();
  await createOfflineHtml();
  console.log("[Offline Build] Done. Open offline/index.html directly in the browser.\n");
}

main().catch((err) => {
  console.error("[Offline Build] Failed:", err);
  process.exit(1);
});
