// VehicleRegistry.js - All 17 vehicles data

export const VEHICLE_REGISTRY = {
  bike: {
    id: 'bike',
    name: 'Bike',
    maxSpeed: 2.6,
    friction: 0.90,
    seats: 2,
    category: 'ground',
    purpose: 'speed',
    width: 56,
    height: 32,
    color: '#00E5FF',
    secondaryColor: '#0099CC',
    description: 'Lightweight, fast, agile—used by default in mid-speed chase segments.',
    acceleration: 1200,
    jumpForce: 600,
    gravity: 2000
  },
  chopper: {
    id: 'chopper',
    name: 'Chopper',
    maxSpeed: 2.0,
    friction: 0.88,
    seats: 3,
    category: 'ground',
    purpose: 'cruiser',
    width: 80,
    height: 36,
    color: '#FF6B35',
    secondaryColor: '#CC5529',
    description: 'Heavy cruiser bike with multiple seats; strong stability, slower turns.',
    acceleration: 900,
    jumpForce: 550,
    gravity: 2000
  },
  jetpack: {
    id: 'jetpack',
    name: 'Jetpack',
    maxSpeed: 2.4,
    friction: 0.92,
    seats: 1,
    category: 'air',
    purpose: 'aerial',
    width: 40,
    height: 48,
    color: '#9A6BFF',
    secondaryColor: '#7A55CC',
    description: 'Personal flight pack; allows vertical freedom and evasion from hazards.',
    acceleration: 1000,
    jumpForce: 800,
    gravity: 1500
  },
  car: {
    id: 'car',
    name: 'Car (Default)',
    maxSpeed: 2.2,
    friction: 0.85,
    seats: 3,
    category: 'ground',
    purpose: 'default',
    width: 72,
    height: 40,
    color: '#FFD700',
    secondaryColor: '#CCAA00',
    description: 'Balanced baseline vehicle; used when no other type is specified.',
    acceleration: 1000,
    jumpForce: 500,
    gravity: 2000
  },
  personal_bike: {
    id: 'personal_bike',
    name: 'Personal Bike',
    maxSpeed: 2.8,
    friction: 0.91,
    seats: 1,
    category: 'ground',
    purpose: 'personal',
    width: 52,
    height: 28,
    color: '#00FF88',
    secondaryColor: '#00CC6A',
    description: 'Single-rider speed bike; highest acceleration among bikes.',
    acceleration: 1400,
    jumpForce: 650,
    gravity: 2000
  },
  personal_chopper: {
    id: 'personal_chopper',
    name: 'Personal Chopper',
    maxSpeed: 2.1,
    friction: 0.87,
    seats: 1,
    category: 'ground',
    purpose: 'personal',
    width: 76,
    height: 32,
    color: '#FF4444',
    secondaryColor: '#CC3333',
    description: 'Solo heavy bike; excellent stability for rough terrain.',
    acceleration: 950,
    jumpForce: 580,
    gravity: 2000
  },
  personal_jetpack: {
    id: 'personal_jetpack',
    name: 'Personal Jetpack',
    maxSpeed: 2.5,
    friction: 0.93,
    seats: 1,
    category: 'air',
    purpose: 'personal',
    width: 36,
    height: 44,
    color: '#AA88FF',
    secondaryColor: '#8866CC',
    description: 'Enhanced jetpack model; faster vertical movement.',
    acceleration: 1100,
    jumpForce: 850,
    gravity: 1400
  },
  personal_car: {
    id: 'personal_car',
    name: 'Personal Car',
    maxSpeed: 2.3,
    friction: 0.86,
    seats: 1,
    category: 'ground',
    purpose: 'personal',
    width: 64,
    height: 36,
    color: '#FFAA00',
    secondaryColor: '#CC8800',
    description: 'Compact sports car; nimble handling, solo driver.',
    acceleration: 1150,
    jumpForce: 520,
    gravity: 2000
  },
  hovercraft: {
    id: 'hovercraft',
    name: 'Hovercraft',
    maxSpeed: 2.7,
    friction: 0.75,
    seats: 2,
    category: 'hover',
    purpose: 'hover',
    width: 84,
    height: 40,
    color: '#00FFFF',
    secondaryColor: '#00CCCC',
    description: 'Hovers above ground; ignores terrain, smooth gliding.',
    acceleration: 1100,
    jumpForce: 0,
    gravity: 1000
  },
  heavy_transport: {
    id: 'heavy_transport',
    name: 'Heavy Transport',
    maxSpeed: 1.5,
    friction: 0.80,
    seats: 6,
    category: 'ground',
    purpose: 'transport',
    width: 120,
    height: 56,
    color: '#888888',
    secondaryColor: '#666666',
    description: 'Large cargo vehicle; slow but seats 6, high HP.',
    acceleration: 600,
    jumpForce: 400,
    gravity: 2200
  },
  buggy: {
    id: 'buggy',
    name: 'Buggy',
    maxSpeed: 2.4,
    friction: 0.88,
    seats: 2,
    category: 'ground',
    purpose: 'offroad',
    width: 68,
    height: 36,
    color: '#FFFF00',
    secondaryColor: '#CCCC00',
    description: 'Off-road vehicle; handles rough terrain well.',
    acceleration: 1050,
    jumpForce: 700,
    gravity: 2000
  },
  mech_proto: {
    id: 'mech_proto',
    name: 'Mech Proto',
    maxSpeed: 2.0,
    friction: 0.85,
    seats: 1,
    category: 'ground',
    purpose: 'mech',
    width: 64,
    height: 80,
    color: '#555577',
    secondaryColor: '#444466',
    description: 'Early-stage battle mech; high HP, heavy knockback immunity.',
    acceleration: 800,
    jumpForce: 550,
    gravity: 2200
  },
  mech_apex: {
    id: 'mech_apex',
    name: 'Mech Apex',
    maxSpeed: 2.3,
    friction: 0.83,
    seats: 1,
    category: 'ground',
    purpose: 'mech',
    width: 72,
    height: 96,
    color: '#667799',
    secondaryColor: '#556688',
    description: 'Advanced version with shoulder cannons; V1 = Boost, V2 = Missile Barrage.',
    acceleration: 850,
    jumpForce: 600,
    gravity: 2200
  },
  skateboard_street: {
    id: 'skateboard_street',
    name: 'Skateboard Street',
    maxSpeed: 2.5,
    friction: 0.90,
    seats: 1,
    category: 'ground',
    purpose: 'skateboard',
    width: 40,
    height: 16,
    color: '#FF88AA',
    secondaryColor: '#CC6688',
    description: 'Street-style board; strong acceleration, low control in air.',
    acceleration: 1300,
    jumpForce: 750,
    gravity: 2000
  },
  tank: {
    id: 'tank',
    name: 'Tank',
    maxSpeed: 1.2,
    friction: 0.70,
    seats: 4,
    category: 'ground',
    purpose: 'combat',
    width: 112,
    height: 64,
    color: '#3D5A3D',
    secondaryColor: '#2A4A2A',
    description: 'Armored combat vehicle; slowest but tankiest, 4 seats.',
    acceleration: 500,
    jumpForce: 300,
    gravity: 2500
  },
  helicopter: {
    id: 'helicopter',
    name: 'Helicopter',
    maxSpeed: 2.8,
    friction: 0.95,
    seats: 4,
    category: 'air',
    purpose: 'aerial',
    width: 96,
    height: 48,
    color: '#44AA44',
    secondaryColor: '#338833',
    description: 'Rotary aircraft; full air mobility, 4 passenger capacity.',
    acceleration: 900,
    jumpForce: 700,
    gravity: 1600
  },
  speedboat: {
    id: 'speedboat',
    name: 'Speedboat',
    maxSpeed: 3.0,
    friction: 0.82,
    seats: 3,
    category: 'water',
    purpose: 'water',
    width: 76,
    height: 32,
    color: '#3399FF',
    secondaryColor: '#2277CC',
    description: 'Water vehicle; fastest top speed, only works on water.',
    acceleration: 1200,
    jumpForce: 0,
    gravity: 2000
  },
  // NEW VEHICLES FROM BAG SYSTEM
  scooter: {
    id: 'scooter',
    name: 'Scooter',
    maxSpeed: 1.8,
    friction: 0.92,
    seats: 1,
    category: 'ground',
    purpose: 'personal',
    width: 28,
    height: 48,
    color: '#FF6B9D',
    secondaryColor: '#CC5580',
    description: 'Maneuverable kick scooter for quick urban travel.',
    acceleration: 1300,
    jumpForce: 550,
    gravity: 2000
  },
  shopping_cart: {
    id: 'shopping_cart',
    name: 'Shopping Cart',
    maxSpeed: 1.2,
    friction: 0.88,
    seats: 1,
    category: 'ground',
    purpose: 'cargo',
    width: 48,
    height: 52,
    color: '#C0C0C0',
    secondaryColor: '#A0A0A0',
    description: 'Surprisingly useful metal cart with cargo capacity.',
    acceleration: 800,
    jumpForce: 400,
    gravity: 2000
  },
  roller_skates: {
    id: 'roller_skates',
    name: 'Roller Skates',
    maxSpeed: 2.2,
    friction: 0.93,
    seats: 1,
    category: 'ground',
    purpose: 'personal',
    width: 32,
    height: 24,
    color: '#FFD700',
    secondaryColor: '#FFA500',
    description: 'Fast roller skates for smooth surfaces and tricks.',
    acceleration: 1400,
    jumpForce: 700,
    gravity: 2000
  },
  hover_disc: {
    id: 'hover_disc',
    name: 'Hover Disc',
    maxSpeed: 1.6,
    friction: 0.78,
    seats: 1,
    category: 'hover',
    purpose: 'hover',
    width: 44,
    height: 12,
    color: '#00FFFF',
    secondaryColor: '#00CCCC',
    description: 'Floating disc platform for hovering above ground.',
    acceleration: 1100,
    jumpForce: 0,
    gravity: 800
  },
  glider: {
    id: 'glider',
    name: 'Glider',
    maxSpeed: 2.0,
    friction: 0.96,
    seats: 1,
    category: 'air',
    purpose: 'aerial',
    width: 80,
    height: 24,
    color: '#87CEEB',
    secondaryColor: '#6495ED',
    description: 'Simple hang glider for graceful gliding flights.',
    acceleration: 900,
    jumpForce: 650,
    gravity: 1200
  },
  balloon_ride: {
    id: 'balloon_ride',
    name: 'Balloon Ride',
    maxSpeed: 1.0,
    friction: 0.95,
    seats: 2,
    category: 'air',
    purpose: 'aerial',
    width: 56,
    height: 80,
    color: '#FF69B4',
    secondaryColor: '#FF1493',
    description: 'Slow but peaceful hot air balloon basket ride.',
    acceleration: 600,
    jumpForce: 500,
    gravity: 800
  },
  sled: {
    id: 'sled',
    name: 'Sled',
    maxSpeed: 2.4,
    friction: 0.80,
    seats: 2,
    category: 'ground',
    purpose: 'speed',
    width: 52,
    height: 20,
    color: '#8B4513',
    secondaryColor: '#654321',
    description: 'Fast sled perfect for snowy slopes and downhill runs.',
    acceleration: 900,
    jumpForce: 600,
    gravity: 2000
  },
  van: {
    id: 'van',
    name: 'Van',
    maxSpeed: 1.8,
    friction: 0.84,
    seats: 3,
    category: 'ground',
    purpose: 'transport',
    width: 88,
    height: 56,
    color: '#4169E1',
    secondaryColor: '#1E3A8A',
    description: 'Heavy utility van with cargo space and durability.',
    acceleration: 850,
    jumpForce: 450,
    gravity: 2200
  },
  bus: {
    id: 'bus',
    name: 'Bus',
    maxSpeed: 1.6,
    friction: 0.78,
    seats: 8,
    category: 'ground',
    purpose: 'transport',
    width: 128,
    height: 64,
    color: '#FFD700',
    secondaryColor: '#FFA500',
    description: 'Large public bus with massive passenger capacity.',
    acceleration: 700,
    jumpForce: 350,
    gravity: 2500
  },
  train: {
    id: 'train',
    name: 'Train',
    maxSpeed: 1.9,
    friction: 0.70,
    seats: 8,
    category: 'ground',
    purpose: 'transport',
    width: 140,
    height: 72,
    color: '#DC143C',
    secondaryColor: '#8B0000',
    description: 'High-capacity train coach with exceptional speed on rails.',
    acceleration: 750,
    jumpForce: 300,
    gravity: 2500
  },
  // Infinite Horizon: The Janitor God - Missy's Bat-Van (Mobile Base)
  bat_van: {
    id: 'bat_van',
    name: "Missy's Bat-Van",
    maxSpeed: 1.7,
    friction: 0.82,
    seats: 4,
    category: 'ground',
    purpose: 'mobile_base',
    width: 96,
    height: 64,
    color: '#1a0033', // Dark purple/black
    secondaryColor: '#6600FF', // Purple accent
    description: "Missy's mobile base and Shadow Army storage vehicle. Opens bag system UI when entered.",
    acceleration: 800,
    jumpForce: 400,
    gravity: 2200,
    isMobileBase: true // Flag to indicate this opens bag system
  }
};

export function getAllVehicles() {
  return Object.values(VEHICLE_REGISTRY);
}

export function getVehicle(id) {
  return VEHICLE_REGISTRY[id];
}

